spring:
  application:
    name: oishii.cms
  profiles:
    active: local
server:
  port: 30010
  servlet:
    context-path: /oishii.cms
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:log4j2.xml